name: nilmtk-env
dependencies:
- python=3.6.4
- Cython>=0.27.3
- bottleneck>=1.2.1
- numpy>=1.13.3
- numexpr>=2.6.4
- pytables
- pandas==0.22.0
- matplotlib
- networkx==2.1
- scipy>=1.0.0
- scikit-learn>=0.19.1
- jupyter
- ipython
- six
- future
- nose
- coverage
- pip
- pip:  # Install packages which are not in conda. Install these using pip:
    - coveralls
    - git+https://github.com/hmmlearn/hmmlearn.git#egg=hmmlearn
    - psycopg2 # not available in conda for Windows.  See issue #462
    - git+https://github.com/nilmtk/nilm_metadata.git#egg=nilm_metadata
    - git+https://github.com/nilmtk/nilmtk.git#egg=nilmtk
    - ipykernel # Needed to get jupyter notebook working with different kernel
